package gui;

import com.formdev.flatlaf.FlatLightLaf;
import core.saveLoad.db.DBManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Connection;
import javax.swing.JCheckBox;

public class DBMenu extends javax.swing.JDialog {

    Main parent;    
    
    public DBMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent=(Main)parent;
        setLocationRelativeTo(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        accept = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        anonUser = new javax.swing.JCheckBox();
        localhost = new javax.swing.JCheckBox();
        passwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Base de Datos");

        jLabel1.setText("Base de Datos");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        accept.setText("Aceptar");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        anonUser.setText("Usuario anónimo");
        anonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anonUserActionPerformed(evt);
            }
        });

        localhost.setText("Base de datos local");
        localhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localhostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(localhost)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accept))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(url, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(user)
                                            .addComponent(passwd)))
                                    .addComponent(anonUser))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(localhost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(anonUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(accept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void anonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anonUserActionPerformed
        
        JCheckBox src = (JCheckBox) evt.getSource();
        
        if(src.isSelected()){
            user.setEnabled(false);
            passwd.setEnabled(false);
        }
        else{
            user.setEnabled(true);
            passwd.setEnabled(true);
        }
    }//GEN-LAST:event_anonUserActionPerformed

    private void localhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localhostActionPerformed
        JCheckBox src = (JCheckBox) evt.getSource();
        
        if(src.isSelected()){
            url.setEnabled(false);
        }
        else{
            url.setEnabled(true);
        }
    }//GEN-LAST:event_localhostActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        DBManager dbmanager;
        
        if(!localhost.isSelected()){
            if(!anonUser.isSelected()){
                dbmanager = new DBManager(url.getText(), user.getText(), passwd.getText());
            }
        
            else{
                dbmanager = new DBManager(url.getText());
            }
        }
        
        else{
            if(!anonUser.isSelected()){
                dbmanager = new DBManager(user.getText(), passwd.getText());
            }

            else{
                dbmanager = new DBManager();
            }
        }
        
        Connection conn = dbmanager.getConnection();
        if(conn!=null){
            parent.setDbConnected(true);
            parent.setDbmanager(dbmanager);
            
            if(dbmanager.checkPrivileges()){
                parent.setAdmin();
                parent.getLabelConnStatus().setText("Estado de Conexión: Admin");   
            }
            
            else{
                parent.setNormalUser();
                parent.getLabelConnStatus().setText("Estado de Conexión: Conectado");    
                
            }           
            JOptionPane.showMessageDialog(rootPane, "Conexión exitosa", "Éxito", JOptionPane.INFORMATION_MESSAGE);   
            this.dispose();
        }
        else{
            parent.setNormalUser();
            parent.setDbConnected(false);
            parent.setDbmanager(null);
            parent.getLabelConnStatus().setText("Estado de Conexión: Desconectado");
            JOptionPane.showMessageDialog(rootPane, "Error al conectar con la base de datos. Comprueba la url y las credenciales", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_acceptActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JCheckBox anonUser;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox localhost;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField url;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
